let urbanJungle = document.getElementById("urbanJungle")
let jsai = document.getElementById("jsAi")
let nieuwsRadar = document.getElementById("nieuwsRadar")
let projectPigeon = document.getElementById("projectPigeon")
let reactNotes = document.getElementById("reactNotes")
let backendApi = document.getElementById("backendApi")
let laravelGallery = document.getElementById("laravelGallery")

urbanJungle.addEventListener("click", () => window.location.href ="./urbanJungle.html")
jsai.addEventListener("click", () => window.location.href ="./jsai.html")
nieuwsRadar.addEventListener("click", () => window.location.href ="./nieuwsradar.html")
projectPigeon.addEventListener("click", () => window.location.href ="./projectPigeon.html")
reactNotes.addEventListener("click", () => window.location.href ="./reactNotes.html")
backendApi.addEventListener("click", () => window.location.href ="./backendApi.html")
laravelGallery.addEventListener("click", () => window.location.href ="./laravelGallery.html")